### ISSUE TITLE
Where is the code for? Research? Can you provide more detail?

### ISSUE THREAD

**Issue by DragonCircle** [guojia-git/spark_feature_extraction#1]
there are few apache spark sql docs on the web, Can you provide more detail about your research? like a paper or something?

**Comment by guojia-git** [comment]
This a course project. Not intended to be used else where.

**Comment by DragonCircle** [comment]
Is this course open accessed?

**Comment by guojia-git** [comment]
I don't think so. And we came up with the the project. Honestly speaking I don't find the project to be of particular high quality. Are there anything specific you are looking for?

**Comment by DragonCircle** [comment]
Yeah, I want to do feature engineering directly on spark dataframe, and deploy it as part of the ML pipeline, but I can not find any material talking about user defined feature engineering, like transform user log data to user session time. If you have any clue about user defined function, that can be applied to a grounped data's column, and produce a data frame of feature per user, plz tell me.

**Comment by guojia-git** [comment]
I haven't been using spark for a while, so I'm afraid I can't help you with that. Good luck with your project
